

sukaldaris_admin:
    resource: "@SukaldarisAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

sukaldaris_info:
    resource: "@SukaldarisInfoBundle/Resources/config/routing.yml"
    prefix:   /

