sukaldaris_security:
    resource: "@SukaldarisSecurityBundle/Controller/"
    type:     annotation
    prefix:   /security

sukaldaris_admin:
    resource: "@SukaldarisAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

sukaldaris_info:
    resource: "@SukaldarisInfoBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google
