# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    my_user_provider.class: Sukaldaris\SecurityBundle\Security\Core\User\MyFOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
    admin.ingrediente:
        class: Sukaldaris\InfoBundle\Admin\IngredienteAdmin
        arguments: [~, Sukaldaris\InfoBundle\Entity\Ingrediente, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Ingrediente }
    admin.categoria:
        class: Sukaldaris\InfoBundle\Admin\CategoriaAdmin
        arguments: [~, Sukaldaris\InfoBundle\Entity\Categoria, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Categoria }
    admin.receta:
        class: Sukaldaris\InfoBundle\Admin\RecetaAdmin
        arguments: [~, Sukaldaris\InfoBundle\Entity\Receta, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Receta }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
