sukaldaris_admin_homepage:
    path:     /
    defaults: { _controller: SukaldarisAdminBundle:Admin:index }

sukaldaris_admin_new_ingrediente:
    path:     /nuevoIngrediente
    defaults: { _controller: SukaldarisAdminBundle:Admin:newIngrediente }
sukaldaris_admin_create_ingrediente:
    path:     /crearIngrediente
    defaults: { _controller: SukaldarisAdminBundle:Admin:createIngrediente }

sukaldaris_admin_new_receta:
    path:     /nuevoReceta
    defaults: { _controller: SukaldarisAdminBundle:Admin:newReceta }
sukaldaris_admin_create_receta:
    path:     /crearReceta
    defaults: { _controller: SukaldarisAdminBundle:Admin:createReceta }

sukaldaris_admin_new_categoria:
    path:     /nuevoCategoria
    defaults: { _controller: SukaldarisAdminBundle:Admin:newCategoria }
sukaldaris_admin_create_categoria:
    path:     /crearCategoria
    defaults: { _controller: SukaldarisAdminBundle:Admin:createCategoria }

sukaldaris_admin_list_ingrediente_edit:
    path:     /listIngredientesEdit/{page}
    defaults: { _controller: SukaldarisAdminBundle:Admin:listIngredientesEdit }
sukaldaris_admin_list_receta_edit:
    path:     /listRecetasEdit/{page}
    defaults: { _controller: SukaldarisAdminBundle:Admin:listRecetasEdit }
sukaldaris_admin_list_categoria_edit:
    path:     /listCategoriasEdit/{page}
    defaults: { _controller: SukaldarisAdminBundle:Admin:listCategoriasEdit }

sukaldaris_admin_list_ingrediente_delete:
    path:     /listIngredientesDelete/{page}
    defaults: { _controller: SukaldarisAdminBundle:Admin:listIngredientesDelete }
sukaldaris_admin_list_receta_delete:
    path:     /listRecetasDelete/{page}
    defaults: { _controller: SukaldarisAdminBundle:Admin:listRecetasDelete }
sukaldaris_admin_list_categoria_delete:
    path:     /listaCategoriasDelete/{page}
    defaults: { _controller: SukaldarisAdminBundle:Admin:listCategoriasDelete }

sukaldaris_admin_goto_edit_ingrediente:
    path:     /editIngrediente/{id}
    defaults: { _controller: SukaldarisAdminBundle:Admin:gotoEditIngrediente }
sukaldaris_admin_goto_edit_receta:
    path:     /editReceta/{id}
    defaults: { _controller: SukaldarisAdminBundle:Admin:gotoEditReceta }
sukaldaris_admin_goto_edit_categoria:
    path:     /editCategoria/{id}
    defaults: { _controller: SukaldarisAdminBundle:Admin:gotoEditCategoria }

sukaldaris_admin_edit_ingrediente:
    path:     /editingIngrediente/{id}
    defaults: { _controller: SukaldarisAdminBundle:Admin:editIngrediente }
sukaldaris_admin_edit_receta:
    path:     /editingReceta/{id}
    defaults: { _controller: SukaldarisAdminBundle:Admin:editReceta }
sukaldaris_admin_edit_categoria:
    path:     /editingCategoria/{id}
    defaults: { _controller: SukaldarisAdminBundle:Admin:editCategoria }

sukaldaris_admin_delete_ingrediente:
    path:     /deletingIngrediente/{id}
    defaults: { _controller: SukaldarisAdminBundle:Admin:deleteIngrediente }
sukaldaris_admin_delete_receta:
    path:     /deletingReceta/{id}
    defaults: { _controller: SukaldarisAdminBundle:Admin:deleteReceta }
sukaldaris_admin_delete_categoria:
    path:     /deletingCategoria/{id}
    defaults: { _controller: SukaldarisAdminBundle:Admin:deleteCategoria }

sukaldaris_json_palabras:
    path:      /palabrasJSON
    defaults: { _controller: SukaldarisAdminBundle:Admin:palabrasJSON}
