sukaldaris_admin_homepage:
    path:     /
    defaults: { _controller: SukaldarisAdminBundle:Admin:index }

sukaldaris_admin_new_ingrediente:
    path:     /nuevoIngrediente
    defaults: { _controller: SukaldarisAdminBundle:Admin:newIngrediente }
sukaldaris_admin_create_ingrediente:
    path:     /crearIngrediente
    defaults: { _controller: SukaldarisAdminBundle:Admin:createIngrediente }

sukaldaris_admin_new_receta:
    path:     /nuevoReceta
    defaults: { _controller: SukaldarisAdminBundle:Admin:newReceta }
sukaldaris_admin_create_receta:
    path:     /crearReceta
    defaults: { _controller: SukaldarisAdminBundle:Admin:createReceta }

sukaldaris_admin_list_ingrediente_edit:
    path:     /listIngredientesEdit/{page}
    defaults: { _controller: SukaldarisAdminBundle:Admin:listIngredientesEdit }
sukaldaris_admin_list_receta_edit:
    path:     /listRecetasEdit/{page}
    defaults: { _controller: SukaldarisAdminBundle:Admin:listRecetasEdit }

sukaldaris_admin_list_ingrediente_delete:
    path:     /listIngredientesDelete/{page}
    defaults: { _controller: SukaldarisAdminBundle:Admin:listIngredientesDelete }
sukaldaris_admin_list_receta_delete:
    path:     /listRecetasDelete/{page}
    defaults: { _controller: SukaldarisAdminBundle:Admin:listRecetasDelete }
