sukaldaris_info_homepage:
    path:     /
    defaults: { _controller: SukaldarisInfoBundle:Info:index }
sukaldaris_info_all:
    path:     /verTodo/{page}
    defaults: { _controller: SukaldarisInfoBundle:Info:verTodo }
sukaldaris_receta:
    path:     /receta/{id}
    defaults: { _controller: SukaldarisInfoBundle:Info:receta }
sukaldaris_search:
    path:     /search
    defaults: { _controller: SukaldarisInfoBundle:Info:search}
sukaldaris_search_results:
    path:     /search/{pattern}
    defaults: { _controller: SukaldarisInfoBundle:Info:searchResults}
