sukaldaris_info_homepage:
    path:     /
    defaults: { _controller: SukaldarisInfoBundle:Info:index }
sukaldaris_info_all:
    path:     /verTodo/{page}
    defaults: { _controller: SukaldarisInfoBundle:Info:verTodo }
sukaldaris_receta:
    path:     /receta/{id}
    defaults: { _controller: SukaldarisInfoBundle:Info:receta }
