<?php

namespace Sukaldaris\InfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngredienteRecetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredienteRecetaRepository extends EntityRepository
{
	
	public function getIngredientesRecetaForReceta($idReceta)
	{
	
    $qb = $this->createQueryBuilder("c");
    $qb
        ->leftjoin("c.receta", "p")
        ->where("p = :idReceta")
        ->setParameter("idReceta", $idReceta);

    return $qb->getQuery()->getResult();

	}

}