<?php

namespace Sukaldaris\InfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngredienteRecetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientesRecetasRepository extends EntityRepository
{
	
	public function getIngredientesRecetaForReceta($idReceta)
	{
	
    $qb = $this->createQueryBuilder("c");
    $qb
        ->leftjoin("c.id_receta", "p")
        ->where("p = :idReceta")
        ->setParameter("idReceta", $idReceta);

    return $qb->getQuery()->getResult();

	}
    public function getIngredientesRecetaForIngrediente($idIngrediente)
    {
    
    $qb = $this->createQueryBuilder("c");
    $qb
        ->leftjoin("c.id_ingrediente", "p")
        ->where("p = :idIngrediente")
        ->setParameter("idIngrediente", $idReceta);

    return $qb->getQuery()->getResult();

    }

}