<?php

namespace Sukaldaris\InfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesRepository extends EntityRepository
{
}
