<?php

namespace Sukaldaris\InfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PalabraClaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalabraClaveRepository extends EntityRepository
{
	public function getPalabrasClaveForReceta($idReceta)
	{
	
    $qb = $this->createQueryBuilder("c");
    $qb
        ->leftjoin("c.recetas", "p")
        ->where("p = :idReceta")
        ->setParameter("idReceta", $idReceta);

    return $qb->getQuery()->getResult();

	}
}
