<?php

namespace Sukaldaris\InfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasoRepository extends EntityRepository
{
	public function getPasosForReceta($idReceta)
	{
	
    $qb = $this->createQueryBuilder("c");
    $qb
        ->leftjoin("c.id_receta", "p")
        ->where("p = :idReceta")
        ->setParameter("idReceta", $idReceta)
        ->addOrderBy('c.numeroPaso', 'ASC');

    return $qb->getQuery()->getResult();

	}
}
